version: "3.7"
services:
  web:
    container_name: container-web
    build:
      context: .
      dockerfile: container-build/web/Dockerfile
    env_file:
      - ./.env
    ports:
      - "8101:80"
    volumes:
      - ../../:/var/www
    depends_on:
      - db

  db:
    container_name: container-db
    image: mysql:5.7
    ports:
      - "3307:3306"
    env_file:
      - ./.env
